baseURL: "http://localhost:1313/"
timeout: 100000
enableGitInfo: true
security:
  exec:
    osEnv:
      - ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME|SSH_AUTH_SOCK|USERPROFILE|XDG_CONFIG_HOME)$']